from setuptools import setup, find_packages

setup(
    name="verl",
    version="0.2.0.dev0",
    description="verl: Volcano Engine Reinforcement Learning for LLM",
    long_description_content_type="text/markdown",
    url="https://github.com/volcengine/verl",
    author="Bytedance - Seed - MLSys",
    author_email="zhangchi.usc1992@bytedance.com, gmsheng@connect.hku.hk",
    license="Apache 2.0",
    packages=find_packages(include=["verl", "verl.*"]),
    install_requires=[
        "accelerate",
        "codetiming",
        "datasets",
        "dill",
        "hydra-core",
        "numpy",
        "pandas",
        "peft",
        "pyarrow>=15.0.0",
        "pybind11",
        "pylatexenc",
        "ray[default]>=2.10",
        "torchdata",
        "tensordict<=0.6.2",
        "transformers<=4.51",
        "wandb",
        "qwen_agent",
        "qwen_vl_utils",
        "polars",
        "easyocr",
    ],
    extras_require={
        "gpu": ["flash-attn"],
        "vllm": ["tensordict<=0.6.2", "vllm<=0.8.3"],
        "test": ["pytest", "pre-commit", "py-spy"],
    },
    python_requires=">=3.10",
)
